### ISSUE TITLE
compiling issue after libsophon is updated to v0.5.0

### ISSUE THREAD

**Issue by shenyunjason** [sophgo/libsophon#7]
hi.
   I am working on soc mode with the branch v23.09-LTS, but I found one compiling issue after libsophon is updated to v0.5.0

cc -c /temp/sophon/libsophon/bmvid/bmcv//src/bmcv_api_jpeg_enc.cpp -o /temp/sophon/libsophon/bmvid/bmcv//obj/src/bmcv_api_jpeg_enc.o
/temp/sophon/libsophon/bmvid/bmcv//src/bmcv_api_jpeg_enc.cpp: In function ‘bm_status_t bmcv_jpeg_enc_one_image(bmcv_jpeg_encoder_t*, bm_image*, void**, size_t*, int, int)’:
/temp/sophon/libsophon/bmvid/bmcv//src/bmcv_api_jpeg_enc.cpp:496:16: error: ‘struct BmJpuJPEGEncParams’ has no member named ‘bs_in_device’
     enc_params.bs_in_device          = bs_in_device;
                ^~~~~~~~~~~~
make[3]: *** [Makefile:216: /temp/sophon/libsophon/bmvid/bmcv//obj/src/bmcv_api_jpeg_enc.o] Error 1
make[2]: *** [bmvid/CMakeFiles/bmcv_lib.dir/build.make:84: bmvid/release/lib/libbmcv.so] Error 2
make[1]: *** [CMakeFiles/Makefile2:1405: bmvid/CMakeFiles/bmcv_lib.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

   It seems that bs_in_device is only updated on pcie mode, on soc, pcie_riscv64 and pcie_arm64 mode, bs_in_device is not added .
   Pls help me check it
Thanks very much

**Comment by sophon-xun** [comment]
Hello sir or madam
     We are very sorry, this is due to a mismatch between the lib file and the header file. We will fix it ASAP. We apologize for any inconvenience caused.
Thank you for your suggestion

**Comment by sophon-xun** [comment]
Now we have fixed this issue and are waiting for the administrator's login. After merging, we will comment again.

**Comment by sophon-xun** [comment]
Hi Sir
    The problem has been fixed now, please try again.
Thank you for your suggestion
